# Generated by Django 4.2 on 2023-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product1_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='carts',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='prdts',
        ),
    ]
